# Homework - Part 2 - Gaussian NB 

We use Gaussian NB to classify the Iris data base. Specifically:

1. Load the iris database using load_iris from sklearn.datasets
2. split the data into train and test so that test size is half the data. Use random state=0
3. Use a Gaussian NB classifier to classify the test data
4. How many incorrect clasisfications do you get?
5. Print the parameters of the model

## Solution

In [65]:
# 1
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score ,precision_score,recall_score,f1_score
# Loading the dataset
from sklearn.datasets import load_iris
iris = load_iris()

In [66]:
# 2 
X=iris.data
y=iris.target
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.5,random_state= 0)

In [67]:
# 3. 
from sklearn.naive_bayes import GaussianNB
gaussian = GaussianNB()
gaussian.fit(X_train, y_train)
Y_pred = gaussian.predict(X_test) 
accuracy_nb=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_gaussian = round(gaussian.score(X_train, y_train) * 100, 2)

cm = confusion_matrix(y_test, Y_pred)
accuracy = accuracy_score(y_test,Y_pred)
precision =precision_score(y_test, Y_pred,average='micro')
recall =  recall_score(y_test, Y_pred,average='micro')
f1 = f1_score(y_test,Y_pred,average='micro')
print('Confusion matrix for Naive Bayes\n',cm)
print('accuracy_Naive Bayes: %.3f' %accuracy)
print('precision_Naive Bayes: %.3f' %precision)
print('recall_Naive Bayes: %.3f' %recall)
print('f1-score_Naive Bayes : %.3f' %f1)

Confusion matrix for Naive Bayes
 [[21  0  0]
 [ 0 30  0]
 [ 0  4 20]]
accuracy_Naive Bayes: 0.947
precision_Naive Bayes: 0.947
recall_Naive Bayes: 0.947
f1-score_Naive Bayes : 0.947


## 4. We get 4/75 incorrect clasisfications 

In [68]:
# 5. The parameters
print(gaussian.class_prior_)
#probability of each class.

[0.38666667 0.26666667 0.34666667]


In [69]:
print(gaussian.theta_)
#mean of each feature per class.

[[4.97586207 3.35862069 1.44827586 0.23448276]
 [5.935      2.71       4.185      1.3       ]
 [6.77692308 3.09230769 5.73461538 2.10769231]]


In [70]:
print(gaussian.sigma_)
# variance of each feature per class

[[0.10321047 0.13208086 0.01629013 0.00846612]
 [0.256275   0.0829     0.255275   0.046     ]
 [0.38869823 0.10147929 0.31303255 0.04763314]]


In [72]:
print(np.sqrt(gaussian.sigma_))
# standart deviation of each feature per class

[[0.32126386 0.36342931 0.12763281 0.0920115 ]
 [0.50623611 0.28792361 0.50524747 0.21447611]
 [0.62345668 0.31855815 0.55949312 0.21825018]]
